package daemon

import (
	"math"
	"strings"
	"time"
)

// SessionType matches the IPC schema enum values.
type SessionType string

const (
	SessionHuman         SessionType = "human"
	SessionAgentAssisted SessionType = "agentAssisted"
	SessionVibeCoding    SessionType = "vibeCoding"
	SessionPairProg      SessionType = "pairProgramming"
	SessionMixed         SessionType = "mixed"
)

// Signal is one data point fed to the classifier.
type Signal struct {
	// Timing
	WriteIntervalMs  int64 // ms between keystrokes/writes
	BurstSize        int   // lines changed in one save
	IdleAfterBurst   time.Duration
	SavesPerMinute   float64

	// Patterns
	HasLargeChunk    bool   // single write > 50 lines
	FilesChanged     int    // distinct files in last window
	TestsUpdated     bool
	CommitMessageLen int

	// Agent fingerprints
	HasAgentComment  bool   // /* generated by ... */ patterns
	AgentToolActive  bool   // Claude Code / Cursor / Copilot process running
	ChatWindowActive bool   // agent chat window in foreground

	// Pair programming
	MultipleCursors  bool   // multiple git authors in last 5 min
}

// Classifier implements the 12-signal weighted session classifier from DETECTION.md.
type Classifier struct {
	baseline *Baseline
	history  []classifySnapshot
}

type classifySnapshot struct {
	sessionType SessionType
	confidence  float64
	at          time.Time
}

// Baseline stores per-project personal norms built over 10+ sessions.
type Baseline struct {
	AvgWriteIntervalMs  float64
	AvgBurstSize        float64
	AvgSavesPerMinute   float64
	SessionCount        int
}

// NewClassifier creates a classifier with the given personal baseline.
func NewClassifier(b *Baseline) *Classifier {
	if b == nil {
		b = &Baseline{
			AvgWriteIntervalMs: 800,
			AvgBurstSize:       3,
			AvgSavesPerMinute:  2,
		}
	}
	return &Classifier{baseline: b}
}

// Classify returns the most likely session type and a confidence score 0–1.
func (c *Classifier) Classify(s Signal) (SessionType, float64) {
	// SessionMixed is initialized here so it can never win via map zero-value
	// accumulation from Signal 12 alone — it only wins via the close-check below.
	scores := map[SessionType]float64{
		SessionHuman:         0,
		SessionAgentAssisted: 0,
		SessionVibeCoding:    0,
		SessionPairProg:      0,
		SessionMixed:         0,
	}

	// ── Signal 1: Write interval (weight 0.15)
	// Human: intervals match personal baseline ±50%
	// Agent: very fast or writes arrive in bursts with no intermediate saves
	if c.baseline.AvgWriteIntervalMs > 0 {
		ratio := float64(s.WriteIntervalMs) / c.baseline.AvgWriteIntervalMs
		if ratio < 0.1 {
			// Extremely fast — agent territory
			scores[SessionVibeCoding] += 0.15
			scores[SessionAgentAssisted] += 0.10
		} else if ratio >= 0.5 && ratio <= 2.0 {
			// Within normal human range
			scores[SessionHuman] += 0.15
		}
	}

	// ── Signal 2: Burst size (weight 0.20)
	if s.BurstSize > 50 {
		scores[SessionVibeCoding] += 0.20
		scores[SessionAgentAssisted] += 0.15
	} else if s.BurstSize > 20 {
		scores[SessionAgentAssisted] += 0.10
		scores[SessionVibeCoding] += 0.08
	} else if s.BurstSize <= 5 {
		// Small, deliberate edits lean human — mid-range is neutral
		scores[SessionHuman] += 0.10
	}

	// ── Signal 3: Large chunk detection (weight 0.18)
	if s.HasLargeChunk {
		scores[SessionVibeCoding] += 0.18
		scores[SessionAgentAssisted] += 0.12
	}
	// No large chunk is neutral — consistent with both human and pair programming

	// ── Signal 4: Saves per minute vs baseline (weight 0.10)
	if c.baseline.AvgSavesPerMinute > 0 {
		ratio := s.SavesPerMinute / c.baseline.AvgSavesPerMinute
		if ratio > 5 {
			scores[SessionVibeCoding] += 0.10
		} else if ratio > 2 {
			scores[SessionAgentAssisted] += 0.07
		} else {
			scores[SessionHuman] += 0.08
		}
	}

	// ── Signal 5: Idle after burst (weight 0.12)
	// Vibe coding pattern: large write then 10–30s of nothing (reviewing)
	if s.HasLargeChunk && s.IdleAfterBurst >= 5*time.Second && s.IdleAfterBurst <= 60*time.Second {
		scores[SessionVibeCoding] += 0.12
	}

	// ── Signal 6: Agent comment patterns (weight 0.15)
	if s.HasAgentComment {
		scores[SessionVibeCoding] += 0.15
		scores[SessionAgentAssisted] += 0.12
	}

	// ── Signal 7: Agent tool running (weight 0.20)
	if s.AgentToolActive {
		scores[SessionAgentAssisted] += 0.20
		scores[SessionVibeCoding] += 0.15
	}

	// ── Signal 8: Chat window active (weight 0.15)
	if s.ChatWindowActive {
		scores[SessionAgentAssisted] += 0.15
	}

	// ── Signal 9: Tests updated (weight 0.08)
	// Human devs tend to update tests; pure vibe coding often doesn't
	if s.TestsUpdated {
		scores[SessionHuman] += 0.08
		scores[SessionAgentAssisted] += 0.04
	} else if s.HasLargeChunk {
		scores[SessionVibeCoding] += 0.06
	}

	// ── Signal 10: Files changed breadth (weight 0.08)
	// Vibe coding often touches many files in one session
	if s.FilesChanged > 10 {
		scores[SessionVibeCoding] += 0.08
	} else if s.FilesChanged > 5 {
		scores[SessionAgentAssisted] += 0.04
	}

	// ── Signal 11: Commit message length (weight 0.05)
	// Very short commit messages correlate with vibe coding
	if s.CommitMessageLen > 0 && s.CommitMessageLen < 20 {
		scores[SessionVibeCoding] += 0.05
	}

	// ── Signal 12: Multiple cursors / authors (weight 0.45)
	// Pair programming is the only session type with multiple active authors —
	// the weight is high because this signal is highly specific when present.
	if s.MultipleCursors {
		scores[SessionPairProg] += 0.45
	}

	// Find winner among the four real types — SessionMixed is decided below,
	// never from accumulated signal scores directly.
	realTypes := []SessionType{SessionHuman, SessionAgentAssisted, SessionVibeCoding, SessionPairProg}
	best, bestScore := SessionHuman, -1.0
	for _, t := range realTypes {
		if scores[t] > bestScore {
			bestScore = scores[t]
			best = t
		}
	}

	// Mixed: two or more real types score within 0.10 of the winner.
	// This means the signals are genuinely ambiguous — classify as mixed.
	var closeCount int
	for _, t := range realTypes {
		if t != best && bestScore-scores[t] < 0.10 && scores[t] > 0.05 {
			closeCount++
		}
	}
	if closeCount >= 2 {
		best = SessionMixed
	}

	// Confidence is the winner's raw score, capped at 1.0.
	confidence := math.Min(bestScore, 1.0)

	snap := classifySnapshot{sessionType: best, confidence: confidence, at: time.Now()}
	c.history = append(c.history, snap)
	if len(c.history) > 100 {
		c.history = c.history[1:]
	}

	return best, confidence
}

// agentFingerprints are patterns in file content or filenames that indicate an agent wrote it.
var agentFingerprints = []string{
	"generated by claude", "co-authored-by: claude",
	"generated by copilot", "generated by cursor",
	"@generated", "// generated", "# generated",
}

// HasAgentFingerprint checks whether content contains known agent signatures.
func HasAgentFingerprint(content string) bool {
	lower := strings.ToLower(content)
	for _, fp := range agentFingerprints {
		if strings.Contains(lower, fp) {
			return true
		}
	}
	return false
}
