// Code generated by scripts/generate-schema.js. DO NOT EDIT.

// Observation — A daemon observation broadcast to all connected clients
export interface Observation {
  id: string;
  kind: 'technical' | 'human' | 'win' | 'question' | 'taste';
  category: string;
  confidence: number;
  text: string;
  agentPrompt?: string;
  // One-line why Flint noticed this — included when confidence < 0.82
  explainWhy?: string;
  timestamp: string;
  filePath?: string;
  lineNumber?: number;
  sessionType?: 'human' | 'agentAssisted' | 'vibeCoding' | 'pairProgramming' | 'mixed';
  // Set when observation matched a footgun pattern
  footgunId?: string;
}

// Dismissal — Sent from extension to daemon when developer taps the dismiss button
export interface Dismissal {
  observationId: string;
  timestamp: string;
}

// SessionState — Broadcast when daemon detects a session state or type transition
export interface SessionState {
  state: 'early' | 'exploration' | 'deepWork' | 'debuggingSpiral' | 'finishing';
  sessionType: 'human' | 'agentAssisted' | 'vibeCoding' | 'pairProgramming' | 'mixed';
  since: string;
}

// DaemonStatus — Full daemon status — returned on status request and broadcast on change
export interface DaemonStatus {
  awareness: 'spark' | 'flame' | 'forge';
  humanLayer: boolean;
  project?: string;
  observationCount: number;
  sessionState?: string;
  sessionType?: string;
  lastObservation?: string;
}

// Subscribe — Sent from client to daemon on connect to begin receiving broadcasts
export interface Subscribe {
  clientType: 'extension' | 'cli';
}

// Ack — Acknowledgement from daemon after processing a dismissal
export interface Ack {
  observationId: string;
  action: 'calibrated' | 'dismissed';
}

// AutoFix — Broadcast when daemon auto-fixes something and stages the change
export interface AutoFix {
  category: string;
  description: string;
  filesChanged: string[];
  timestamp: string;
}

// TripwireFired — Broadcast when a flint watch pattern is touched — bypasses all time gates
export interface TripwireFired {
  tripwireId: string;
  pattern: string;
  filePath?: string;
  timestamp: string;
}

// FlintMessage — discriminated union of every IPC message type.
export type FlintMessage =
  | Observation
  | Dismissal
  | SessionState
  | DaemonStatus
  | Subscribe
  | Ack
  | AutoFix
  | TripwireFired;
