#!/usr/bin/env node
// Code generator — reads shared/schema.json, outputs Go structs and TS interfaces.
// Run with: node scripts/generate-schema.js

'use strict';

const fs   = require('fs');
const path = require('path');

const ROOT       = path.join(__dirname, '..');
const SCHEMA     = path.join(ROOT, 'shared', 'schema.json');
const GO_OUT     = path.join(ROOT, 'core', 'pkg', 'schema', 'schema.go');
const TS_OUT     = path.join(ROOT, 'extension', 'src', 'ipc', 'messages.ts');

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

function pascal(s) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function constName(structName, field, value) {
  return `${structName}${pascal(field)}${pascal(value)}`;
}

// JSON Schema property → Go type
function goType(prop, required) {
  const ptr = !required;
  let base;
  if (prop.enum)              base = 'string';
  else if (prop.type === 'string')  base = 'string';
  else if (prop.type === 'number')  base = 'float64';
  else if (prop.type === 'integer') base = 'int';
  else if (prop.type === 'boolean') base = 'bool';
  else if (prop.type === 'array') {
    const item = prop.items?.type === 'string' ? 'string' : 'interface{}';
    // slices are already reference types — no pointer needed
    return `[]${item}`;
  }
  else base = 'interface{}';

  return ptr ? `*${base}` : base;
}

// JSON Schema property → TypeScript type
function tsType(prop) {
  if (prop.enum)              return prop.enum.map(v => `'${v}'`).join(' | ');
  if (prop.type === 'string') return 'string';
  if (prop.type === 'number' || prop.type === 'integer') return 'number';
  if (prop.type === 'boolean') return 'boolean';
  if (prop.type === 'array') {
    const item = prop.items?.type === 'string' ? 'string' : 'unknown';
    return `${item}[]`;
  }
  return 'unknown';
}

// ---------------------------------------------------------------------------
// Go generation
// ---------------------------------------------------------------------------

function generateGo(messages) {
  const lines = [];
  const consts = [];

  lines.push('// Code generated by scripts/generate-schema.js. DO NOT EDIT.');
  lines.push('');
  lines.push('package schema');
  lines.push('');

  for (const [msgName, def] of Object.entries(messages)) {
    const name  = pascal(msgName);
    const props = def.properties || {};
    const req   = new Set(def.required || []);

    lines.push(`// ${name} — ${def.description}`);
    lines.push(`type ${name} struct {`);

    for (const [field, prop] of Object.entries(props)) {
      const typ     = goType(prop, req.has(field));
      const omit    = req.has(field) ? '' : ',omitempty';
      const goField = pascal(field);

      if (prop.description) {
        lines.push(`\t// ${prop.description}`);
      }
      lines.push(`\t${goField} ${typ} \`json:"${field}${omit}"\``);

      if (prop.enum) {
        for (const val of prop.enum) {
          consts.push(`\t${constName(name, field, val)} = "${val}"`);
        }
      }
    }

    lines.push('}');
    lines.push('');
  }

  if (consts.length > 0) {
    lines.push('// Enum constants — use these instead of bare string literals.');
    lines.push('const (');
    lines.push(consts.join('\n'));
    lines.push(')');
    lines.push('');
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// TypeScript generation
// ---------------------------------------------------------------------------

function generateTS(messages) {
  const lines = [];
  const names = [];

  lines.push('// Code generated by scripts/generate-schema.js. DO NOT EDIT.');
  lines.push('');

  for (const [msgName, def] of Object.entries(messages)) {
    const name  = pascal(msgName);
    const props = def.properties || {};
    const req   = new Set(def.required || []);

    names.push(name);

    lines.push(`// ${name} — ${def.description}`);
    lines.push(`export interface ${name} {`);

    for (const [field, prop] of Object.entries(props)) {
      const typ      = tsType(prop);
      const optional = req.has(field) ? '' : '?';

      if (prop.description) {
        lines.push(`  // ${prop.description}`);
      }
      lines.push(`  ${field}${optional}: ${typ};`);
    }

    lines.push('}');
    lines.push('');
  }

  lines.push('// FlintMessage — discriminated union of every IPC message type.');
  lines.push(`export type FlintMessage =`);
  lines.push('  | ' + names.join('\n  | ') + ';');
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const schema   = JSON.parse(fs.readFileSync(SCHEMA, 'utf8'));
const messages = schema.messages;

const goCode = generateGo(messages);
const tsCode = generateTS(messages);

fs.mkdirSync(path.dirname(GO_OUT), { recursive: true });
fs.mkdirSync(path.dirname(TS_OUT), { recursive: true });

fs.writeFileSync(GO_OUT, goCode, 'utf8');
fs.writeFileSync(TS_OUT, tsCode, 'utf8');

console.log(`✓  ${path.relative(ROOT, GO_OUT)}`);
console.log(`✓  ${path.relative(ROOT, TS_OUT)}`);
