// Detects which agent (if any) is currently active in the developer's environment.
// This feeds Signal.AgentToolActive in the session classifier.

import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

export type AgentName = 'claude-code' | 'cursor' | 'copilot' | 'windsurf' | 'unknown';

export interface AgentInfo {
  name: AgentName;
  detected: boolean;
}

// Known agent process signatures
const agentProcessPatterns: Record<AgentName, RegExp> = {
  'claude-code': /claude(-code)?/i,
  'cursor':      /cursor/i,
  'copilot':     /github.copilot/i,
  'windsurf':    /windsurf/i,
  'unknown':     /^$/,
};

// Known agent file fingerprints in content
const agentContentSignatures: Record<AgentName, string[]> = {
  'claude-code': ['co-authored-by: claude', 'generated by claude'],
  'cursor':      ['generated by cursor', '@cursor'],
  'copilot':     ['generated by github copilot', '@generated'],
  'windsurf':    ['generated by windsurf'],
  'unknown':     [],
};

// Detect from VS Code extension host context — checks active extensions.
export function detectFromExtensions(activeExtensionIds: string[]): AgentInfo {
  const ids = activeExtensionIds.map(id => id.toLowerCase());

  if (ids.some(id => id.includes('cursor')))    return { name: 'cursor',    detected: true };
  if (ids.some(id => id.includes('copilot')))   return { name: 'copilot',   detected: true };
  if (ids.some(id => id.includes('windsurf')))  return { name: 'windsurf',  detected: true };
  if (ids.some(id => id.includes('claude')))    return { name: 'claude-code', detected: true };

  return { name: 'unknown', detected: false };
}

// Detect from file content — looks for agent fingerprints in changed files.
export function detectFromContent(content: string): AgentInfo {
  const lower = content.toLowerCase();

  for (const [name, sigs] of Object.entries(agentContentSignatures) as [AgentName, string[]][]) {
    if (name === 'unknown') continue;
    if (sigs.some(sig => lower.includes(sig))) {
      return { name, detected: true };
    }
  }

  return { name: 'unknown', detected: false };
}

// Detect Claude Code specifically by checking for its socket / lock file.
export function detectClaudeCode(): boolean {
  const tmpDir = os.tmpdir();
  try {
    const entries = fs.readdirSync(tmpDir);
    return entries.some((e: string) => e.startsWith('claude') && e.endsWith('.sock'));
  } catch {
    return false;
  }
}
