// Code generated by scripts/generate-schema.js. DO NOT EDIT.

package schema

// Observation — A daemon observation broadcast to all connected clients
type Observation struct {
	Id string `json:"id"`
	Kind string `json:"kind"`
	Category string `json:"category"`
	Confidence float64 `json:"confidence"`
	Text string `json:"text"`
	AgentPrompt *string `json:"agentPrompt,omitempty"`
	// One-line why Flint noticed this — included when confidence < 0.82
	ExplainWhy *string `json:"explainWhy,omitempty"`
	Timestamp string `json:"timestamp"`
	FilePath *string `json:"filePath,omitempty"`
	LineNumber *int `json:"lineNumber,omitempty"`
	SessionType *string `json:"sessionType,omitempty"`
	// Set when observation matched a footgun pattern
	FootgunId *string `json:"footgunId,omitempty"`
}

// Dismissal — Sent from extension to daemon when developer taps the dismiss button
type Dismissal struct {
	ObservationId string `json:"observationId"`
	Timestamp string `json:"timestamp"`
}

// SessionState — Broadcast when daemon detects a session state or type transition
type SessionState struct {
	State string `json:"state"`
	SessionType string `json:"sessionType"`
	Since string `json:"since"`
}

// DaemonStatus — Full daemon status — returned on status request and broadcast on change
type DaemonStatus struct {
	Awareness string `json:"awareness"`
	HumanLayer bool `json:"humanLayer"`
	Project *string `json:"project,omitempty"`
	ObservationCount int `json:"observationCount"`
	SessionState *string `json:"sessionState,omitempty"`
	SessionType *string `json:"sessionType,omitempty"`
	LastObservation *string `json:"lastObservation,omitempty"`
}

// Subscribe — Sent from client to daemon on connect to begin receiving broadcasts
type Subscribe struct {
	ClientType string `json:"clientType"`
}

// Ack — Acknowledgement from daemon after processing a dismissal
type Ack struct {
	ObservationId string `json:"observationId"`
	Action string `json:"action"`
}

// AutoFix — Broadcast when daemon auto-fixes something and stages the change
type AutoFix struct {
	Category string `json:"category"`
	Description string `json:"description"`
	FilesChanged []string `json:"filesChanged"`
	Timestamp string `json:"timestamp"`
}

// TripwireFired — Broadcast when a flint watch pattern is touched — bypasses all time gates
type TripwireFired struct {
	TripwireId string `json:"tripwireId"`
	Pattern string `json:"pattern"`
	FilePath *string `json:"filePath,omitempty"`
	Timestamp string `json:"timestamp"`
}

// Enum constants — use these instead of bare string literals.
const (
	ObservationKindTechnical = "technical"
	ObservationKindHuman = "human"
	ObservationKindWin = "win"
	ObservationKindQuestion = "question"
	ObservationKindTaste = "taste"
	ObservationSessionTypeHuman = "human"
	ObservationSessionTypeAgentAssisted = "agentAssisted"
	ObservationSessionTypeVibeCoding = "vibeCoding"
	ObservationSessionTypePairProgramming = "pairProgramming"
	ObservationSessionTypeMixed = "mixed"
	SessionStateStateEarly = "early"
	SessionStateStateExploration = "exploration"
	SessionStateStateDeepWork = "deepWork"
	SessionStateStateDebuggingSpiral = "debuggingSpiral"
	SessionStateStateFinishing = "finishing"
	SessionStateSessionTypeHuman = "human"
	SessionStateSessionTypeAgentAssisted = "agentAssisted"
	SessionStateSessionTypeVibeCoding = "vibeCoding"
	SessionStateSessionTypePairProgramming = "pairProgramming"
	SessionStateSessionTypeMixed = "mixed"
	DaemonStatusAwarenessSpark = "spark"
	DaemonStatusAwarenessFlame = "flame"
	DaemonStatusAwarenessForge = "forge"
	SubscribeClientTypeExtension = "extension"
	SubscribeClientTypeCli = "cli"
	AckActionCalibrated = "calibrated"
	AckActionDismissed = "dismissed"
)
